import { FormEvent, useEffect, useState } from 'react';
import { adminApiClient } from '../api/client';
interface AssetDto { id:string;reference:string;ownerId:string;ownerType:string;lifecycleState:string;securityClassification:string;retentionCategory:string;metadata?:{originalFilename?:string;mimeType?:string;byteSize?:number};createdAt:string }
interface AssetPage {items:AssetDto[];hasMore:boolean;nextCursor:string|null}
export function AssetAdminPage(){const[items,setItems]=useState<AssetDto[]>([]);const[cursor,setCursor]=useState<string|null>(null);const[hasMore,setHasMore]=useState(false);const[error,setError]=useState<string|null>(null);const[filters,setFilters]=useState({q:'',lifecycleState:'',securityClassification:'',ownerType:'',ownerId:'',mimeTypePrefix:'',createdFrom:'',createdTo:''});
const load=async(reset=true)=>{try{setError(null);const p=new URLSearchParams({limit:'50'});Object.entries(filters).forEach(([k,v])=>{if(!v.trim())return;p.set(k,(k==='createdFrom'||k==='createdTo')?new Date(v).toISOString():v.trim())});if(!reset&&cursor)p.set('cursor',cursor);const r=await adminApiClient.request<AssetPage>(`/admin/assets?${p}`);setItems(prev=>reset?r.items:[...prev,...r.items]);setCursor(r.nextCursor);setHasMore(r.hasMore)}catch(e){setError(e instanceof Error?e.message:'Failed to load assets.')}};useEffect(()=>{void load(true)},[]);const submit=(e:FormEvent)=>{e.preventDefault();void load(true)};
return <div className="space-y-5"><div><h2 className="text-2xl font-black text-[#142B5F]">Asset Center</h2><p className="text-sm text-[#203442]/60">Canonical EAP assets, lifecycle/security state, ownership, and clean-delivery readiness.</p></div>{error&&<div className="rounded-xl bg-red-50 p-3 text-red-700">{error}</div>}
<form onSubmit={submit} className="grid gap-2 rounded-2xl border bg-white p-4 md:grid-cols-4"><input value={filters.q} onChange={e=>setFilters(v=>({...v,q:e.target.value}))} placeholder="Search ID/reference/owner/file" className="rounded-xl border p-2"/><input value={filters.lifecycleState} onChange={e=>setFilters(v=>({...v,lifecycleState:e.target.value}))} placeholder="Lifecycle state" className="rounded-xl border p-2"/><input value={filters.securityClassification} onChange={e=>setFilters(v=>({...v,securityClassification:e.target.value}))} placeholder="Security classification" className="rounded-xl border p-2"/><input value={filters.mimeTypePrefix} onChange={e=>setFilters(v=>({...v,mimeTypePrefix:e.target.value}))} placeholder="MIME prefix" className="rounded-xl border p-2"/><input value={filters.ownerType} onChange={e=>setFilters(v=>({...v,ownerType:e.target.value}))} placeholder="Owner type" className="rounded-xl border p-2"/><input value={filters.ownerId} onChange={e=>setFilters(v=>({...v,ownerId:e.target.value}))} placeholder="Owner ID" className="rounded-xl border p-2"/><input type="datetime-local" value={filters.createdFrom} onChange={e=>setFilters(v=>({...v,createdFrom:e.target.value}))} className="rounded-xl border p-2" aria-label="Created from"/><input type="datetime-local" value={filters.createdTo} onChange={e=>setFilters(v=>({...v,createdTo:e.target.value}))} className="rounded-xl border p-2" aria-label="Created to"/><button className="rounded-xl bg-[#142B5F] px-4 py-2 font-bold text-white md:col-span-4">Filter</button></form>
<div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-xs"><thead><tr><th className="p-3">Asset</th><th className="p-3">Owner</th><th className="p-3">MIME</th><th className="p-3">Lifecycle</th><th className="p-3">Security</th><th className="p-3">Retention</th></tr></thead><tbody>{items.map(a=><tr key={a.id} className="border-t"><td className="p-3"><div className="font-bold">{a.metadata?.originalFilename??a.reference}</div><code>{a.id}</code></td><td className="p-3"><code>{a.ownerType}:{a.ownerId}</code></td><td className="p-3">{a.metadata?.mimeType??'—'}</td><td className="p-3 font-bold">{a.lifecycleState}</td><td className="p-3">{a.securityClassification}</td><td className="p-3">{a.retentionCategory}</td></tr>)}</tbody></table></div>{hasMore&&<button onClick={()=>void load(false)} className="rounded-xl border px-4 py-2 font-bold">Load more</button>}</div>}
