import { FormEvent, useEffect, useState } from 'react';
import { adminApiClient } from '../api/client';

interface AuditRecordDto { id:string; reference:string; action:string; category:string; severity:string; actor:{actorId:string;actorType:string}; target:{targetId:string;targetType:string}; source:string; timestamp:string; correlationReference?:string; traceReference?:string; contextMetadata:unknown }
interface AuditPage { items: AuditRecordDto[]; hasMore:boolean; nextCursor:string|null }

export function AuditCenterPage() {
  const [items,setItems]=useState<AuditRecordDto[]>([]); const [cursor,setCursor]=useState<string|null>(null); const [hasMore,setHasMore]=useState(false); const [error,setError]=useState<string|null>(null); const [selected,setSelected]=useState<AuditRecordDto|null>(null);
  const [filters,setFilters]=useState({actorId:'',action:'',category:'',correlationId:''});
  const [integrity,setIntegrity]=useState<'UNKNOWN'|'PASS'|'FAIL'>('UNKNOWN');
  const load=async(reset=true)=>{try{setError(null);const p=new URLSearchParams({limit:'50'});Object.entries(filters).forEach(([k,v])=>v.trim()&&p.set(k,v.trim()));if(!reset&&cursor)p.set('cursor',cursor);const r=await adminApiClient.request<AuditPage>(`/admin/audit/records?${p}`);setItems(prev=>reset?r.items:[...prev,...r.items]);setCursor(r.nextCursor);setHasMore(r.hasMore)}catch(e){setError(e instanceof Error?e.message:'Failed to load audit records.')}};
  useEffect(()=>{void load(true);adminApiClient.request<{status:'PASS'|'FAIL'}>('/admin/audit/integrity').then(r=>setIntegrity(r.status)).catch(()=>setIntegrity('FAIL'))},[]);
  const submit=(e:FormEvent)=>{e.preventDefault();void load(true)};
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-black text-[#142B5F]">Immutable Audit Center</h2><p className="text-sm text-[#203442]/60">Read-only cross-domain evidence. No edit/delete action is exposed.</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${integrity==='PASS'?'bg-emerald-50 text-emerald-700':integrity==='FAIL'?'bg-red-50 text-red-700':'bg-slate-100 text-slate-600'}`}>Integrity: {integrity}</span><a href="/api/v1/admin/audit/export?format=csv&limit=100" className="rounded-xl border px-3 py-1 text-xs font-bold">Export bounded CSV</a></div></div>{error&&<div className="rounded-xl bg-red-50 p-3 text-red-700">{error}</div>}
    <form onSubmit={submit} className="grid gap-2 rounded-2xl border bg-white p-4 md:grid-cols-5">{(['actorId','action','category','correlationId'] as const).map(k=><input key={k} value={filters[k]} onChange={e=>setFilters(v=>({...v,[k]:e.target.value}))} placeholder={k} className="rounded-xl border p-2 text-sm"/>)}<button className="rounded-xl bg-[#142B5F] px-4 py-2 text-sm font-bold text-white">Filter</button></form>
    <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full text-left text-xs"><thead><tr><th className="p-3">Time</th><th className="p-3">Actor</th><th className="p-3">Action</th><th className="p-3">Domain</th><th className="p-3">Target</th><th className="p-3">Trace</th></tr></thead><tbody>{items.map(item=><tr key={item.id} onClick={()=>setSelected(item)} className="cursor-pointer border-t hover:bg-[#DDEFF2]/30"><td className="p-3">{new Date(item.timestamp).toLocaleString()}</td><td className="p-3"><code>{item.actor.actorId}</code></td><td className="p-3 font-bold">{item.action}</td><td className="p-3">{item.category}</td><td className="p-3"><code>{item.target.targetType}:{item.target.targetId}</code></td><td className="p-3"><code>{item.traceReference??item.correlationReference??'—'}</code></td></tr>)}</tbody></table></div>
    {hasMore&&<button onClick={()=>void load(false)} className="rounded-xl border px-4 py-2 text-sm font-bold">Load older evidence</button>}
    {selected&&<div className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><h3 className="font-black">Audit drill-down · {selected.reference}</h3><button onClick={()=>setSelected(null)}>×</button></div><pre className="mt-3 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(selected,null,2)}</pre></div>}
  </div>;
}
