export enum CmsContentType {
  ARTICLE = 'ARTICLE',
  STUDY_GUIDE = 'STUDY_GUIDE',
  NEWS = 'NEWS',
  FAQ = 'FAQ',
  CHECKLIST = 'CHECKLIST',
  STATIC_PAGE = 'STATIC_PAGE',
  ANNOUNCEMENT = 'ANNOUNCEMENT',
  LANDING_PAGE = 'LANDING_PAGE',
  CONTENT_BLOCK = 'CONTENT_BLOCK',
}
