export enum AIExecutionStatus {
  RECEIVED = 'RECEIVED',
  QUEUED = 'QUEUED',
  ACCEPTED = 'ACCEPTED',
  RUNNING = 'RUNNING',
  RETRYING = 'RETRYING',
  BLOCKED = 'BLOCKED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  TIMED_OUT = 'TIMED_OUT'
}
