export enum AIProviderType {
  INTERNAL_MOCK = 'INTERNAL_MOCK',
  EXTERNAL_LLM = 'EXTERNAL_LLM',
  OPENAI_COMPATIBLE = 'OPENAI_COMPATIBLE',
  ANTHROPIC = 'ANTHROPIC',
  GOOGLE_GENERATIVE_AI = 'GOOGLE_GENERATIVE_AI',
  SELF_HOSTED = 'SELF_HOSTED'
}
